# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.City')),
            ],
        ),
    ]
