# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(null=True, to='deals.Category'),
        ),
    ]
