# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_auto_20180211_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deals.Offer'),
            preserve_default=False,
        ),
    ]
