# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_comment_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email_comment',
            field=models.CharField(max_length=100),
        ),
    ]
